### ISSUE TITLE
Placeholder for checkboxes/radio inputs are not parsed in PDF

### ISSUE THREAD

**Issue by mcnickel** [Jako/FormIt2PDF#2]
The placeholder for a checkbox/radio returns the placeholder name (`[[+placeholdername]]`) in the generated PDF.

Using `formit2pdf.formfields` placeholder in the template returns the correct checkbox/radio input value in the generated PDF (a `,` is added to checkbox values, but this is technically not a problem).
Placeholders for text/textarea/mail inputs are also parsed correctly.

Environment:
MODX 2.8.4
PHP 8.0.28
FormIt2PDF 1.0.1

**Comment by Jako** [comment]
This is fixed in https://github.com/Jako/FormIt2PDF/commit/fa1e96795638dafd1facf82549522d12109c92ed and published in version 1.0.2.
